config/routes.rb
Rails.application.routes.draw do
  scope module: "web" do

    root "informations#index"

    get "/", to: "informations#index", as: "home"

    resource :users, only: [:new, :create], path_names: { new: "sign_up" } do
      resource :session, only: [], path: "" do
        get :new, path: "sign_in", as: :new
        post :create, path: "sign_in"
        delete :destroy, path: "sign_out", as: :destroy
      end
    end

    namespace :admin do
      root "education_programs#index"

      resources :groups
      resources :tests
      resources :courses
      resources :education_programs
    end

    namespace :account do
      root "education_programs#index"

      resources :education_programs, only: [:index, :show]
      resources :courses, only: [:index, :show]
      resources :tests, only: [:index, :show]
    end

  end
end

app/models/group.rb
class Group < ApplicationRecord
  include EducationProgramStudentable

  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users

  validates :title, presence: true
end

app/controllers/web/admin/groups_controller.rb
class Web::Admin::GroupsController < Web::Admin::ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit]

  def index
    respond_with(@groups = Group.all)
  end

  def show
  end

  def new
    respond_with(@group = Group.new)
  end

  def create
    respond_with(@group = Group.create(group_params), location: -> { admin_groups_path })
  end

  def edit
  end

  def update
    @group.update(group_params)
    respond_with(@group, location: -> { admin_groups_path })
  end

  def destroy
    respond_with(@group.destroy, location: -> { admin_groups_path })
  end

  private

  def group_params
    params.require(:group).permit(:title, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.all.order(:last_name).decorate
  end
end

app/controllers/web/groups_controller.rb
class Web::GroupsController < Web::ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit]

  def index
    respond_with(@groups = Group.all)
  end

  def show
  end

  def new
    respond_with(@group = Group.new)
  end

  def create
    respond_with(@group = Group.create(group_params), location: -> { groups_path })
  end

  def edit
  end

  def update
    @group.update(group_params)
    respond_with(@group, location: -> { groups_path })
  end

  def destroy
    respond_with(@group.destroy, location: -> { groups_path })
  end

  private

  def group_params
    params.require(:group).permit(:title, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.all.order(:last_name).decorate
  end
end

app/views/web/admin/groups/_form.slim
= simple_form_for [:admin, @group], validate: true do |f|
  = f.input :title, autofocus: true
  = f.association :users, as: :select, multiple: true, collection: @users.map{ |u| [u.short_name, u.id] }, input_html: { class: "chosen-select" }

  = f.button :submit, "Save", class: "btn-primary"

app/views/web/admin/groups/edit.slim
.row
  .col-md-6
    h1 Edit Group

    = render "form"

app/views/web/admin/groups/index.slim
.row
  .col-md-6
    h1 Groups

    = link_to "New", new_admin_group_path, class: "btn btn-primary"

    table.table.table-striped
      thead
        tr
          th title
          th
      tbody
        - @groups.each do |group|
          tr
            td= link_to group.title, [:admin, group]
            td
              => link_to "Edit", edit_admin_group_path(group), class: "btn btn-primary btn-xs"
              = link_to "Destroy", admin_group_path(group), method: :delete,
                data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-xs"

app/views/web/admin/groups/new.slim
.row
  .col-md-6
    h1 New Group

    = render "form"

app/views/web/admin/groups/show.slim
.row
  .col-md-6
    h1= @group.title
    = link_to "Edit", edit_admin_group_path(@group), class: "btn btn-primary"
    - if @group.users.any?
      ul
        - @group.users.decorate.each do |user|
          li= user.short_name