config/routes.rb
Rails.application.routes.draw do
  scope module: "web" do

    root "informations#index"

    get "/", to: "informations#index", as: "home"

    resource :users, only: [:new, :create], path_names: { new: "sign_up" } do
      resource :session, only: [], path: "" do
        get :new, path: "sign_in", as: :new
        post :create, path: "sign_in"
        delete :destroy, path: "sign_out", as: :destroy
      end
    end

    namespace :admin do
      root "education_programs#index"

      resources :groups
      resources :tests
      resources :courses
      resources :education_programs
    end

    namespace :account do
      root "education_programs#index"

      resources :education_programs, only: [:index, :show]
      resources :courses, only: [:index, :show]
      resources :tests, only: [:index, :show]
    end

  end
end

app/models/education_program.rb
class EducationProgram < ApplicationRecord
  has_many :education_program_students, dependent: :destroy
  has_many :users, through: :education_program_students, source: :student, source_type: "User"
  has_many :groups, through: :education_program_students, source: :student, source_type: "Group"

  has_many :education_program_assignments, dependent: :destroy
  has_many :tests, through: :education_program_assignments, source: :assignment, source_type: "Test"
  has_many :courses, through: :education_program_assignments, source: :assignment, source_type: "Course"

  validates :title, :description, presence: true
end

app/controllers/web/account/education_programs_controller.rb
class Web::Account::EducationProgramsController < Web::Account::ApplicationController
  before_action :set_education_program, only: [:show]

  def index
    respond_with(@education_programs = current_user.education_programs)
  end

  def show
  end

  private

  def set_education_program
    @education_program = EducationProgram.find(params[:id])
  end
end

app/controllers/web/admin/education_programs_controller.rb
class Web::Admin::EducationProgramsController < Web::Admin::ApplicationController
  before_action :set_education_program, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit]
  before_action :set_groups, only: [:new, :edit]
  before_action :set_tests, only: [:new, :edit]
  before_action :set_cources, only: [:new, :edit]

  def index
    respond_with(@education_programs = EducationProgram.all)
  end

  def show
  end

  def new
    respond_with(@education_program = EducationProgram.new)
  end

  def create
    respond_with(@education_program = EducationProgram.create(education_program_params), location: -> { admin_education_programs_path })
  end

  def edit
  end

  def update
    @education_program.update(education_program_params)
    respond_with(@education_program, location: -> { admin_education_programs_path })
  end

  def destroy
    respond_with(@education_program.destroy, location: -> { admin_education_programs_path })
  end

  private

  def education_program_params
    params.require(:education_program)
      .permit(:title, :description, user_ids: [], group_ids: [], test_ids: [], course_ids: [])
  end

  def set_education_program
    @education_program = EducationProgram.find(params[:id])
  end

  def set_users
    @users = User.all.decorate
  end

  def set_groups
    @groups = Group.all
  end

  def set_tests
    @tests = Test.all
  end

  def set_cources
    @cources = Course.all
  end
end

app/controllers/web/education_programs_controller.rb
class Web::EducationProgramsController < Web::ApplicationController
  before_action :set_education_program, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit]
  before_action :set_groups, only: [:new, :edit]
  before_action :set_tests, only: [:new, :edit]
  before_action :set_cources, only: [:new, :edit]

  def index
    respond_with(@education_programs = EducationProgram.all)
  end

  def show
  end

  def new
    respond_with(@education_program = EducationProgram.new)
  end

  def create
    respond_with(@education_program = EducationProgram.create(education_program_params), location: -> { education_programs_path })
  end

  def edit
  end

  def update
    @education_program.update(education_program_params)
    respond_with(@education_program, location: -> { education_programs_path })
  end

  def destroy
    respond_with(@education_program.destroy, location: -> { education_programs_path })
  end

  private

  def education_program_params
    params.require(:education_program)
      .permit(:title, :description, user_ids: [], group_ids: [], test_ids: [], course_ids: [])
  end

  def set_education_program
    @education_program = EducationProgram.find(params[:id])
  end

  def set_users
    @users = User.all.decorate
  end

  def set_groups
    @groups = Group.all
  end

  def set_tests
    @tests = Test.all
  end

  def set_cources
    @cources = Course.all
  end
end

app/views/web/education_programs/_form.slim
= simple_form_for @education_program do |f|
  = f.input :title, autofocus: true
  = f.input :description
  fieldset
    legend Students
    = f.association :groups, as: :select, multiple: true, collection: @groups.map{ |g| [g.title, g.id] }, input_html: { class: "chosen-select" }
    = f.association :users, as: :select, multiple: true, collection: @users.map{ |u| [u.short_name, u.id] }, input_html: { class: "chosen-select" }

  fieldset
    legend Assignments
    = f.association :courses, as: :select, multiple: true, collection: @cources.map{ |c| [c.title, c.id] }, input_html: { class: "chosen-select" }
    = f.association :tests, as: :select, multiple: true, collection: @tests.map{ |t| [t.title, t.id] }, input_html: { class: "chosen-select" }

  = f.button :submit, "Save", class: "btn-primary"

app/views/web/education_programs/index.slim
.row
  .col-md-6
    h1 Education Programs

    = link_to "New", new_education_program_path, class: "btn btn-primary"

    - if @education_programs.any?
      table.table.table-striped
        thead
          tr
            th title
            th
        tbody
          - @education_programs.each do |education_program|
            tr
              td= link_to education_program.title, education_program
              td
                => link_to "Edit", edit_education_program_path(education_program), class: "btn btn-primary btn-xs"
                = link_to "Destroy", education_program_path(education_program), method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-xs"
    - else
      h3 No education program. Please create one

app/views/web/education_programs/show.slim
.row
  .col-md-6
    h1= @education_program.title
    div= @education_program.description
    => link_to "Edit", edit_education_program_path(@education_program), class: "btn btn-primary"
    = link_to "New", new_education_program_path, class: "btn btn-primary"
.row
  .col-md-6
    h2 Students
    - if @education_program.groups.any?
      h3 Groups
      ol
        - @education_program.groups.each do |group|
          li= group.title
    - if @education_program.users.any?
      h3 Users
      ol
        - @education_program.users.each do |user|
          li= user.short_name

.row
  .col-md-6
    h2 Assignments
    - if @education_program.courses.any?
      h3 Courses
      ol
        - @education_program.courses.each do |course|
          li= link_to course.title, course
    - if @education_program.tests.any?
      h3 Tests
      ol
        - @education_program.tests.each do |test|
          li= link_to test.title, test