config/routes.rb
Rails.application.routes.draw do
  scope module: "web" do

    root "informations#index"

    get "/", to: "informations#index", as: "home"

    resource :users, only: [:new, :create], path_names: { new: "sign_up" } do
      resource :session, only: [], path: "" do
        get :new, path: "sign_in", as: :new
        post :create, path: "sign_in"
        delete :destroy, path: "sign_out", as: :destroy
      end
    end

    namespace :admin do
      root "education_programs#index"

      resources :groups
      resources :tests
      resources :courses
      resources :education_programs
    end

    namespace :account do
      root "education_programs#index"

      resources :education_programs, only: [:index, :show]
      resources :courses, only: [:index, :show]
      resources :tests, only: [:index, :show]
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/education_programable.rb
module EducationProgramAssignmentable
  extend ActiveSupport::Concern

  included do
    has_many :education_program_assignments, as: :assignment, dependent: :destroy
    has_many :education_programs, through: :education_program_assignments
  end
end

app/models/course.rb
class Course < ApplicationRecord
  include EducationProgramAssignmentable

  has_many :education_materials, dependent: :destroy
  has_many :tests, through: :education_materials, source: :material, source_type: "Test"

  validates :title, :description, presence: true
end

app/models/education_material.rb
class EducationMaterial < ApplicationRecord
  belongs_to :course
  belongs_to :material, polymorphic: true
end

app/models/education_program.rb
class EducationProgram < ApplicationRecord
  has_many :education_program_students, dependent: :destroy
  has_many :users, through: :education_program_students, source: :student, source_type: "User"
  has_many :groups, through: :education_program_students, source: :student, source_type: "Group"

  has_many :education_program_assignments, dependent: :destroy
  has_many :tests, through: :education_program_assignments, source: :assignment, source_type: "Test"
  has_many :courses, through: :education_program_assignments, source: :assignment, source_type: "Course"

  validates :title, :description, presence: true
end

app/models/education_program_assignment.rb
class EducationProgramAssignment < ApplicationRecord
  belongs_to :education_program
  belongs_to :assignment, polymorphic: true
end

app/models/education_program_student.rb
class EducationProgramStudent < ApplicationRecord
  belongs_to :education_program
  belongs_to :student, polymorphic: true
end

app/models/group.rb
class Group < ApplicationRecord
  include EducationProgramStudentable

  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users

  validates :title, presence: true
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/test.rb
class Test < ApplicationRecord
  include EducationProgramAssignmentable

  has_many :education_materials, as: :material, dependent: :destroy

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include EducationProgramStudentable

  has_many :groups_users, dependent: :destroy
  has_many :groups, through: :groups_users

  validates :first_name, :last_name, :email, presence: true

  has_secure_password

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]).decorate if session[:user_id]
  end
end

app/controllers/web/courses_controller.rb
class Web::CoursesController < Web::ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_tests, only: [:new, :edit]

  def index
    respond_with(@courses = Course.all)
  end

  def show
  end

  def new
    respond_with(@course = Course.new)
  end

  def create
    respond_with(@course = Course.create(course_params), location: -> { courses_path })
  end

  def edit
  end

  def update
    @course.update(course_params)
    respond_with(@course, location: -> { courses_path })
  end

  def destroy
    respond_with(@course.destroy)
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, test_ids: [])
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def set_tests
    @tests = Test.all
  end
end

app/controllers/web/groups_controller.rb
class Web::GroupsController < Web::ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit]

  def index
    respond_with(@groups = Group.all)
  end

  def show
  end

  def new
    respond_with(@group = Group.new)
  end

  def create
    respond_with(@group = Group.create(group_params), location: -> { groups_path })
  end

  def edit
  end

  def update
    @group.update(group_params)
    respond_with(@group, location: -> { groups_path })
  end

  def destroy
    respond_with(@group.destroy, location: -> { groups_path })
  end

  private

  def group_params
    params.require(:group).permit(:title, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.all.order(:last_name).decorate
  end
end

app/controllers/web/informations_controller.rb
class Web::InformationsController < Web::ApplicationController
  def index
    @courses = Course.all
    @tests = Test.all
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
  end

  def create
    user = User.find_by_email(session_params[:email])
    if user.try(:authenticate, session_params[:password])
      session[:user_id] = user.id
      redirect_to account_root_path
    else
      render :new
    end
  end

  def destroy
    respond_with(session.delete(:user_id), location: -> { root_path })
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/web/tests_controller.rb
class Web::TestsController < Web::ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  def index
    respond_with(@tests = Test.all)
  end

  def show
  end

  def new
    respond_with(@test = Test.new)
  end

  def create
    respond_with(@test = Test.create(test_params), location: -> { tests_path })
  end

  def edit
  end

  def update
    @test.update(test_params)
    respond_with(@test, location: -> { tests_path })
  end

  def destroy
    respond_with(@test.destroy, location: -> { tests_path })
  end

  private

  def test_params
    params.require(:test).permit(:title, :description)
  end

  def set_test
    @test = Test.find(params[:id])
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def new
    respond_with(@user = User.new)
  end

  def create
    respond_with(@user = User.create(user_params), location: -> { root_path })
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin.slim
doctype html
html
  head
    title Education
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"

  body
    = nav_bar brand: "Education Admin Panel", responsive: true, inverse: true do
      = menu_group do
        = menu_item "Education Programs", admin_education_programs_path
        = menu_divider
        = menu_item "Groups", admin_groups_path
        = menu_divider
        = menu_item "Courses", admin_courses_path
        = menu_divider
        = menu_item "Tests", admin_tests_path

      = menu_group pull: :right do
        - if current_user
          = menu_item current_user.short_name, account_root_path
          = menu_divider
          = menu_item "Sign out", destroy_users_session_path, method: :delete
        - else
          = menu_item "Sign in", new_users_session_path
          = menu_divider
          = menu_item "Sign up", new_users_path

    .container
      .row
        = bootstrap_flash
        = yield

app/views/layouts/application.slim
doctype html
html
  head
    title Education
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"

  body
    = nav_bar brand: "Education", responsive: true do
      = menu_group do
        - if current_user
          = menu_item "Your Programs", account_education_programs_path
          = menu_item "Courses", account_courses_path
          = menu_item "Tests", account_tests_path

      = menu_group pull: :right do
        - if current_user
          = menu_item current_user.short_name, account_root_path
          = menu_divider
          - if current_user.admin?
            = menu_item "AdminPanel", admin_root_path
            = menu_divider
          = menu_item "Sign out", destroy_users_session_path, method: :delete
        - else
          = menu_item "Sign in", new_users_session_path
          = menu_divider
          = menu_item "Sign up", new_users_path

    .container
      .row
        = bootstrap_flash
        = yield